version = 1

test_patterns = ["spec/**"]

exclude_patterns = ["index.js"]

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
