name: Dependabot auto-rename
on:
    pull_request_target:
        types:
            - opened
            - edited
            - reopened
        branches:
            - main
            - next
        paths:
            - 'package.json'

permissions:
    pull-requests: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v1
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'
            - name: Rename PR title
              run: |
                  gh pr edit '$PR_URL' --title 'build(deps-dev): bump % ${{ steps.dependabot-metadata.outputs.dependency-names }}@${{ steps.dependabot-metadata.outputs.new-version }}'
